// import this after install `@mdi/font` package
import '@mdi/font/css/materialdesignicons.css';

import 'vuetify/styles';
import { createVuetify } from 'vuetify';

export default defineNuxtPlugin(app => {
  const vuetify = createVuetify({
    theme: {
      defaultTheme: 'regularDark',
      themes: {
        regularLight: {
          dark: false,
          colors: {
            primary: '#FFD54F',
            secondary: '#9575CD',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#BDBDBD',
            wrongGradient: '#E0E0E0',
            unknown: '#e5e5e5',
            unknownGradient: '#f2f2f2',
          },
        },
        regularDark: {
          dark: true,
          colors: {
            primary: '#9575CD',
            secondary: '#FFD54F',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#616161',
            wrongGradient: '#757575',
            unknown: '#424242',
            unknownGradient: '#4f4f4f',
          },
        },
        jungleLight: {
          dark: false,
          colors: {
            primary: '#B2FF59',
            secondary: '#388E3C',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#BDBDBD',
            wrongGradient: '#E0E0E0',
            unknown: '#e5e5e5',
            unknownGradient: '#f2f2f2',
          },
        },
        jungleDark: {
          dark: true,
          colors: {
            primary: '#388E3C',
            secondary: '#B2FF59',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#616161',
            wrongGradient: '#757575',
            unknown: '#424242',
            unknownGradient: '#4f4f4f',
          },
        },
        flamingoLight: {
          dark: false,
          colors: {
            primary: '#F48FB1',
            secondary: '#EC407A',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#BDBDBD',
            wrongGradient: '#E0E0E0',
            unknown: '#e5e5e5',
            unknownGradient: '#f2f2f2',
          },
        },
        flamingoDark: {
          dark: true,
          colors: {
            primary: '#EC407A',
            secondary: '#F48FB1',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#616161',
            wrongGradient: '#757575',
            unknown: '#424242',
            unknownGradient: '#4f4f4f',
          },
        },
        WhurdleLight: {
          dark: false,
          colors: {
            primary: '#00B0FF',
            secondary: '#F50057',
            error: '#FF1744',
            info: '#42A5F5',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#BDBDBD',
            wrongGradient: '#E0E0E0',
            unknown: '#e5e5e5',
            unknownGradient: '#f2f2f2',
          },
        },
        whurdleDark: {
          dark: true,
          colors: {
            primary: '#00B0FF',
            secondary: '#F50057',
            error: '#FF1744',
            info: '#42A5F5',
            success: '#4CAF50',
            warning: '#FFC107',
            correct: '#4CAF50',
            correctGradient: '#81C784',
            misplaced: '#FFC107',
            misplacedGradient: '#FFE082',
            wrong: '#616161',
            wrongGradient: '#757575',
            unknown: '#424242',
            unknownGradient: '#4f4f4f',
            background: '#1A237E',
            card: '#311B92'
          },
        },
      },
    },
  });
  app.vueApp.use(vuetify);
});
